---
name: Update requirements files

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Generate requirements
        run: bash scripts/poetry-export.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update requirements{-dev}.txt
