---
name: Python Unittests

on:
  push:
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry config virtualenv.in-project true
          poetry config virtualenv.path .venv
          source .venv/bin/activate
          echo "VENV=.venv/bin/activate" >>"$GITHUB_ENV"
      - name: Run Tests    
        run: python -m unittest discover -s tests 
